import { SoftwareFiltersConfig } from './types';
export const SOFTWARE_FILTERS: SoftwareFiltersConfig = {
  exclude: [
    /^\{.*\}$/,
    /^mstsc-/,
    /^mspaint-/,
    /^Xbox/,
    /^WindowsApp/,
    /^Windows App/,
    /^Windows Web/,
    /^Windows Package/,
    /^WinApp/,
    /^Widgets/,
    /^KB\d+/i,
    /^Update for Windows/i,
    /^Security Update for/i,
    /^Hotfix for/i,
    /^Microsoft Visual C\+\+ \d+ Redistributable/i,
    /^Microsoft \.NET/i,
    /^\.NET Framework/i,
    /^\.NET Core/i,
    /^\.NET Runtime/i,
    /^Microsoft Edge Update/i,
    /^Microsoft Edge WebView/i,
    /^Windows Software Development Kit/i,
    /^Windows Driver Package/i,
    /^Intel\(R\) Processor Graphics/i,
    /^Intel\(R\) Management Engine/i,
    /^Realtek High Definition Audio/i,
    /^Microsoft Office \d+ Click-to-Run/i,
    /^MSXML \d+/i,
    /^vcredist/i,
    /^DirectX/i,
    /AMD/i,
    /@BIOS/i,
    /NVIDIA/i,
    /ACA &#38; MEP 2022 Object Enabler/i,
    /AIDA64 Extreme v7.50/i,
    /APP Center/i,
    /Adobe Refresh Manager/i,
    /^Aplicaciones de Microsoft 365 para negocios/i,
    /AppUp.IntelGraphicsExperience/i,
    /Asistente para actualización/i,
    /^Asistente para actualización a Windows/i,
    /^Asistente para la instalación de Windows/i,

    /Aplicaciones destacadas de Autodesk/i,
    /^AppServ 8.4.0/i,
    /AppUp.ThunderboltControlCenter/i,
    /^AutoCAD 2022 Language Pack/i,
    /AutoCAD Mechanical 2022 - English/i,
    /AutoCAD Open in Desktop/i,
    /Autodesk App Manager/i,
    /Autodesk AutoCAD Mechanical 2022 - English/i,
    /Autodesk Desktop Connect Service/i,
    /Autodesk Desktop Connect Service 8.1.0/i,
    /Autodesk Guided Tutorial Plugin/i,
    /Autodesk Guided Tutorial Plugin 8.4.0/i,
    /Autodesk Inventor Professional 2022 - English	/i,
    /microsoft windowscommunicationsapps/i,
    /X-Mouse Button Control 2.20.5	/i,
    /Cortana/i,
    /Game/i,
    /Internet Explorer/i,
    /Autodesk Inventor Content Center Libraries 2022 (Desktop Content)	/i,
    /Autodesk Inventor Professional 2022 - English	/i,
    /Autodesk Inventor Professional 2022 English/i,
    /Autodesk Material Library/i,
    /Autodesk Network License Manager/i,
    //i,
    //i,
    //i,
    //i,
    /Edge/i,
    /^Copilot$/i,  // Excluir solo "Copilot" exactamente
  ],
  
  // Patrones para normalizar nombres de software
  normalize: [
    { pattern: /^(Adobe Acrobat)(?:\s+DC|\s+\d+|\s+Reader|\s+Pro|\s+\(64-bits\))?.*$/i, replacement: '$1' },
    { pattern: /^(draw\.io)\s+.*$/i, replacement: '$1' },
    { pattern: /^(WinRAR)\s+.*$/i, replacement: '$1' },
    { pattern: /^Clipchamp(\.Clipchamp)?$/i, replacement: 'Clipchamp' },
  ]
};
