import { SoftwareFiltersConfig } from './types';
export const SOFTWARE_FILTERS: SoftwareFiltersConfig = {
  exclude: [
    //Inician con
    /^\.NET Core/i,
    /^\.NET Framework/i,
    /^\.NET Runtime/i,
    /^AppServ 8.4.0/i,
    /^Asistente para actualización a Windows/i,
    /^Asistente para la instalación de Windows/i,
    /^AutoCAD 2022 Language Pack/i,
    /^Copilot$/i,
    /^DirectX/i,
    /^Hotfix for/i,
    /^KB\d+/i,
    /^LocalServiceComponents/i,
    /^Microsoft/i,
    /^MSXML \d+/i,
    /^mspaint-/,
    /^mstsc-/,
    /^Paquete /,
    /^Realtek High Definition Audio/i,
    /^REX Inventor/i,
    /^Security Update for/i,
    /^Update for Windows/i,
    /^vcredist/i,
    /^Widgets/,
    /^WinApp/,
    /^Windows App/,
    /^Windows Package/,
    /^Windows Software Development Kit/i,
    /^Windows Driver Package/i,
    /^Windows Web/,
    /^WindowsApp/,
    /^\{.*\}$/,

    //Contienen
    /@BIOS/i,
    /ACA &#38; MEP 2022 Object Enabler/i,
    /Adobe Refresh Manager/i,
    /AIDA64 Extreme v7.50/i,
    /AMD/i,
    /APP Center/i,
    /Aplicaciones destacadas de Autodesk/i,
    /AppUp.IntelGraphicsExperience/i,
    /AppUp.ThunderboltControlCenter/i,
    /Asistente para actualización/i,
    /AutoCAD Mechanical 2022 - English/i,
    /AutoCAD Open in Desktop/i,
    /Autodesk App Manager/i,
    /Autodesk AutoCAD Mechanical 2022 - English/i,
    /Autodesk Desktop Connect Service/i,
    /Autodesk Desktop Connect Service 8.1.0/i,
    /Autodesk Guided Tutorial Plugin/i,
    /Autodesk Guided Tutorial Plugin 8.4.0/i,
    /Autodesk Inventor Content/i,
    /Autodesk Inventor Professional 2022 - English/i,
    /Autodesk Inventor Professional 2022 English/i,
    /Autodesk Material Library/i,
    /Autodesk Network License Manager/i,
    /Cortana/i,
    /Edge/i,
    /Game/i,
    /Guardar en la versión web y para dispositivos móviles de Autodesk/i,
    /GLPI Agent 1.15/i,
    /Intel/i,
    /Internet Explorer/i,
    /NVIDIA/i,
    /Microsoft Office ActionsServer/i,
    /Microsoft 365 Copilot/i,
    /microsoft windowscommunicationsapps/i,
    /Click-to-Run/i,
    /OfficePushNotificationsUtility/i,
    /Update/i,
    /Upgrade/i,
    /X-Mouse Button Control 2.20.5/i,
    /Xbox/i,
  ],
  
  // Patrones para incluir software que empiece con Microsoft
  include: [
    /^Microsoft PowerAutomateDesktop/i,
    /^Microsoft PowerPoint 2016/i,
    /^Microsoft PowerPoint LTSC - es-es\.proof/i,
    /^Microsoft 365 - es-es/i,
    /^Microsoft Office P/i,
    /^Microsoft OneDrive$/i,
    /^Microsoft Project/i,
  ],
  
  // Patrones para normalizar nombres de software
  normalize: [
    { pattern: /^(Adobe Acrobat)(?:\s+DC|\s+\d+|\s+Reader|\s+Pro|\s+\(64-bits\))?.*$/i, replacement: '$1' },
    { pattern: /^AutoCAD(?:\s+Mechanical)?(?:\s+2022)?$/i, replacement: 'Autodesk AutoCAD 2022' },
    { pattern: /^Clipchamp(\.Clipchamp)?$/i, replacement: 'Clipchamp' },
    { pattern: /^(draw\.io)\s+.*$/i, replacement: '$1' },
    { pattern: /^(Foxit PDF)\s+.*$/i, replacement: '$1' },
    { pattern: /^(Kaspersky)\s+.*$/i, replacement: '$1' },
    { pattern: /^(Aplicaciones de Microsoft 365 para negocios)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Microsoft Office 365 (Licencia)' },
    { pattern: /^(Microsoft 365 Apps for business)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Microsoft Office 365 (Licencia)' },
    { pattern: /^(Microsoft 365 - es-es)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Microsoft Office 2016' },
    { pattern: /^(Microsoft Office Professional Plus 2019)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Microsoft Office 2019' },
    { pattern: /^(Microsoft Office Profesional Plus 2019)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Microsoft Office 2019' },
    { pattern: /^(Microsoft Office Professional Plus 2016)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Microsoft Office 2016' },
    { pattern: /^(Microsoft Office Profesional Plus 2016)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Microsoft Office 2016' },
    { pattern: /^(Microsoft PowerPoint 2016)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Microsoft Office 2016' },
    { pattern: /^(Microsoft PowerPoint LTSC)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Microsoft Office 2016' },
    { pattern: /^(Microsoft Office LTSC Professional Plus 2021 - en-us)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Microsoft Office 2021' },
    { pattern: /^(Microsoft Project Professional 2021)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Project 2021' },
    { pattern: /^(Microsoft Project Profesional 2021)(?:\s+-\s+\w+-\w+(?:\.\w+)?)?$/i, replacement: 'Project 2021' },
    { pattern: /^(Microsoft Project Professional 2016)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Project 2016' },
    { pattern: /^(Microsoft Project Profesional 2016)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Project 2016' },
    { pattern: /^(Microsoft Project)(?:\s+-\s+\w+-\w+)?$/i, replacement: 'Project 2021' },
    { pattern: /^Microsoft PowerAutomateDesktop\s*$/i, replacement: 'Power Automate' },
    { pattern: /^(Python)\s+.*$/i, replacement: '$1' },
    { pattern: /^(PowerToys)\s+.*$/i, replacement: '$1' },
    { pattern: /^(WinRAR)\s+.*$/i, replacement: '$1' },
  ]
};
